// <auto-generated />
namespace ExemploWebForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2_add_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_add_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202008121959154_2_add_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
