// <auto-generated />
namespace ExemploWebForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _1_inicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1_inicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202008121944451_1_inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
